### ISSUE TITLE
Bitdefender is marking files 'infected with Atc4.Detection'

### ISSUE THREAD

**Issue by Arnocode** [tronscan/tronscan-desktop#10]
Tronscan.exe is unable to start, because Bitdefender is marking a lot of files as virus.
It looks like almost every file gets marked (.exe, .html, .json, .svg, .js etc.)

For example (Thread detected and moved to quarantine):
The file c:\users\[uname]\appdata\roaming\tr\locales\fil.pak is infected with Atc4.Detection and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.

Examples of files with a Thread detected:
tronscan-windows-x64\tronscan-win32-x64\tronscan.exe
c:\users\..\appdata\roaming\tr\locales\fil.pak
c:\users\..\appdata\roaming\tr\locales\am.pak 
c:\users\..\appdata\roaming\tr\locales\uk.pak
so *.pak in that directory
c:\users\..\appdata\roaming\tr\resources\app\index.html
c:\users\..\appdata\roaming\tr\resources\app\89b8b83913a5ae583a84200683618b53.svg
c:\users\..\appdata\roaming\tr\resources\app\manifest.json
 c:\users\..\appdata\roaming\tr\resources\app\index.html
c:\users\..\appdata\roaming\tron-explorer-desktop\gpucache\data_0
c:\users\..\appdata\roaming\tr\resources\app\static\js\main.54fd04c1.js

**Comment by Rovak** [comment]
I've tried uploading some of the reported files to online virusscanners and none of them detected any virusses. Seems like your virusscanner is reporting false positives
