### ISSUE TITLE
program just keep loading

### ISSUE THREAD

**Issue by itogs** [tronscan/tronscan-desktop#11]
trying to open the wallet using ledger nano s, it open once and manage to send fund, now wallet wont open just keep loading

**Comment by itogs** [comment]
any fix? wallet wont open and just keep loading

**Comment by Rovak** [comment]
I've got reports that virusscanner could be the issue, try excluding the folder and then open the client

**Comment by Barakas1125** [comment]
I'm experiencing the same issue as well. It happened to be this morning, took me about 30 minutes and numerous attempts for wallet to finally load. Now i'm trying to load wallet and the same problem.

**Comment by itogs** [comment]
yap, it works by turning off my virus scanner, it works for awhile and now stop working again.

**Comment by Rovak** [comment]
are you getting any errors when it stops working?
