### ISSUE TITLE
A Javascript error occured in the main process (TRX + Ledger Nano S)

### ISSUE THREAD

**Issue by pitcha** [tronscan/tronscan-desktop#12]
1. I downloaded Ledger Nano Live
2. I installed Tron app on Ledger
3. I downloaded and installed Tronscan. 
4. On Tronscan, I clicked on Open Wallet, then clicked on Ledger Nano S
5. I opened Tron app on ledger
6. While the the Tronscan was loading the error message appeared.

```A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'unsubscribe' of undefined
    at Timeout._onTimeout (/Applications/Tronscan.app/Contents/Resources/app/index.js:5475:15)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

**Comment by Rovak** [comment]
Try this version https://github.com/tronscan/tronscan-desktop/releases/download/1.1.1/Tronscan-mac-x64.zip, it should resolve the problem
