### ISSUE TITLE
Wallet not loading using ledger nano s

### ISSUE THREAD

**Issue by Barakas1125** [tronscan/tronscan-desktop#16]
This morning i opened my Tronscan wallet connected my ledger nano s. I followed all the instructions and the wallet wouldn't open. It took me about 30 minutes and numerous tries logging in and out my ledger app as well as quitting tronscan app. I finally got in. Now i'm trying to access my wallet to transfer coins and i'm experiencing the same problem.

<img width="1552" alt="screen shot 2018-07-23 at 1 49 46 pm" src="https://user-images.githubusercontent.com/41578633/43094068-f0e878a6-8e7f-11e8-84e4-a84fc9d4bc3a.png">

**Comment by RayMetz100** [comment]
My ledger is inconsistent on non tron coins too.  I sometimes find I have to reboot my windows 10 PC and then the Ledger works fine.  I haven't seen this problem with tron yet, but I won't be surprised if it happens.
