### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by LeeStewie** [tronscan/tronscan-desktop#18]
Following the instructions from the Ledger help guide to access my tron wallet, I'm getting an error after I select Ledger on the Open Wallet screen. It reads as the following:

> Uncaught Exception:
> TypeError: Cannot read property 'unsubscribe' of undefined
>  at Timeout._onTimeout (C:\Program Files\Tronscan\resources\app\index.js:5487:15)
>  at ontimeout (timers.js.475:11)
>  at tryOnTimeout (timers.js:310:5)
>  at Timer.listOnTimeout (timers.js.270:5)

Hope that's enough info to resolve!

**Comment by Rovak** [comment]
@LeeStewie something went wrong with the node modules in the latest version. I just replaced it, please try downloading 1.1.1 again and it should work

**Comment by LeeStewie** [comment]
That did the trick. However, when I tried to freeze my coins, I also got exactly the same error message.

**Comment by LeeStewie** [comment]
I've just tried to freeze my coins again and sadly experiencing the same issue. Any ideas @Rovak ?

**Comment by Rovak** [comment]
i haven't heard of anyone else having this problem. if this problem still persists then feel free to reopen this issue

**Comment by LeeStewie** [comment]
@Rovak Hi, I've just tried again and sadly I'm still getting exactly the same error. What further information do you require from me to get this fixed?

**Comment by LeeStewie** [comment]
Just to update you, as I've managed to get past it.

After posting my error above, I then logged out. However, I experienced the same problem when trying to log back in via my Ledger.

I decided to delete Tronscan and re-download. Whilst I think this is the same version as I had before, trying the freshly downloaded version seems to have resolved the problem.
