### ISSUE TITLE
merging accounts

### ISSUE THREAD

**Issue by morristico** [tronscan/tronscan-desktop#2]
I had opened a wallet before i had downloaded the desktop app tronscan, to enable the ledger now that i have downloaded the app it gives me new account that doesnt show my balance, is there a way to merge the wallet of even let the ledger open my old account with all my trx ?

**Comment by SnearK6354** [comment]
Hello sir, ledger can’t use your precious wallet PK. The PK from ledger nano is stored inside the ledger nano secure element.

To connect to your previous wallet you need to use the PK that was provided to you upon wallet creation.
No way to merge it with ledger.

However you can freely send the coin from your previous wallet to the ledger wallet (no fees on Tron).
