### ISSUE TITLE
is there anyone who can tell me why I get lost on tronscan.org trx for the second time I had TRX 7,298148 in my wallet I send to binance.nl 0,298148 TRX in my wallet on tronscan.org are now 7 trx there should have been 7000 trx how can this be, this is the second time I have lost trx again

### ISSUE THREAD

**Issue by rogerseggelinck** [tronscan/tronscan-desktop#29]
is there anyone who can tell me why I lost trx on tronscan.org
![see](https://user-images.githubusercontent.com/42588736/44426948-6b5e0e80-a590-11e8-802e-c15b7af954f3.png)
![see2](https://user-images.githubusercontent.com/42588736/44426969-7add5780-a590-11e8-8221-399a787af37b.png)

 for the second time
I had TRX 7,298148 in my wallet
I send to binance.nl 0,298148 TRX
in my wallet on tronscan.org are now 7 trx there should have been 7000 trx
how can this be, this is the second time I have lost trx again

**Comment by SnearK6354** [comment]
Are you sure you had 7000 trx to begin with. 7,290 is 7.29, not 7 thousand and 290.

How much did you receive on Binance ?

**Comment by Rovak** [comment]
i checked your transaction history at https://tronscan.org/#/address/TRiyCnxaZCt6mvNMEQ8y8aTkcc2RH7nDqS/transactions and you only transferred around 15k into your account which are now frozen. The numbers look to be correct

**Comment by rogerseggelinck** [comment]
Hallo Roy volgens mij ben je nederlander dus als je het niet erg vindt typ ik in het nederlands

Als de 2 foto`s bekijkt zie je dat er verschillende stortingen op mijn account zijn gemaakt door TMEQ4hu7DtLTHPn6qPsYktk1QGdTbAyTEK<https://tronscan.org/#/address/TMEQ4hu7DtLTHPn6qPsYktk1QGdTbAyTEK>
Nadat deze stortingen zijn gedaan heb ik naar binance.nl  0,298148 overgemaakt
Je ziet op de tweede foto nog maar 7 trx staan dit zou toch 7,00000 moeten zijn



Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: Roy van Kaathoven <notifications@github.com>
Verzonden: Tuesday, August 21, 2018 11:17:40 PM
Aan: tronscan/tronscan-desktop
CC: rogerseggelinck; Author
Onderwerp: Re: [tronscan/tronscan-desktop] is there anyone who can tell me why I get lost on tronscan.org trx for the second time I had TRX 7,298148 in my wallet I send to binance.nl 0,298148 TRX in my wallet on tronscan.org are now 7 trx there should have been 7...


i checked your transaction history at https://tronscan.org/#/address/TRiyCnxaZCt6mvNMEQ8y8aTkcc2RH7nDqS/transactions and you only transferred around 15k into your account which are now frozen. The numbers look to be correct

**Comment by Rovak** [comment]
Zou je een lijstje kunnen maken van de transacties die je naar het account hebt verstuurd dan kan ik er verder onderzoek naar doen. Of een screenshot van je binance withdrawals

**Comment by rogerseggelinck** [comment]
Hallo Roy
Eerst even een bedankje voor je snelle reactie
Volgens mij ben ik een beetje dom en is 1,159073 maar 1 trx en geen 1000
Volgens mij moet ik mijn dvd speler lade ook als koffie beker houder gebruiken
Maar ieder geval bedankt voor je reactie en mag je in een deuk liggen achter je pc waarschijnlijk was ik de slimste deze week

Mvg
Roger

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: Roy van Kaathoven <notifications@github.com>
Verzonden: Tuesday, August 21, 2018 11:57:05 PM
Aan: tronscan/tronscan-desktop
CC: rogerseggelinck; Author
Onderwerp: Re: [tronscan/tronscan-desktop] is there anyone who can tell me why I get lost on tronscan.org trx for the second time I had TRX 7,298148 in my wallet I send to binance.nl 0,298148 TRX in my wallet on tronscan.org are now 7 trx there should have been 7...


Zou je een lijstje kunnen maken van de transacties die je naar het account hebt verstuurd dan kan ik er verder onderzoek naar doen. Of een screenshot van je binance withdrawals
