### ISSUE TITLE
Unable to create a second Ledger Wallet

### ISSUE THREAD

**Issue by Duff-Paddy** [tronscan/tronscan-desktop#3]
I created a test wallet using Ledger, rubbish password and didn't save keys etc because it was just a test to see how it worked. Nor did I send any TRX to it thankfully but now I cannot create a second / new wallet on the Ledger for proper use.

I go to 'create wallet' on tronscan desktop, use a proper password, save the keys and file properly and it takes me into the new wallet account, however if i log out and attempt to log back in using the Ledger, it takes me to the test wallet again.

Is there a way to flush the old wallet info from the Ledger? I have uninstalled the tron wallet app on the Ledger, then re-installed it but still takes me to test wallet.

**Comment by tronfrance** [comment]
You don't create your wallet, the Ledger Nano S will do it based on your seed phrase.
I created a test wallet using Ledger, rubbish password and didn't save keys  ==> No, in reality the Ledger created a PK from its own Hardware Secure Element, and showed you the adress.
You don't have any keys to save and no password to set. 

The Ledger USB pen drive contains the PK (but it never displays it)

**Comment by tronfrance** [comment]
Is there a way to flush the old wallet info from the Ledger? I have uninstalled the tron wallet app on the Ledger, then re-installed it but still takes me to test wallet.
==> No, you can't flush the ledger wallet easily because it's created from the Hardware Secure Element.

If you restore entirely your Ledger (re-initialise it), then you will create a new HSE PK combination, and therefore a new tron walllet address.

BUT BE CAREFUL, BY DOING SO YOU'LL ALSO CHANGE ALL OTHER CRYPTO ACCOUNT YOU HAVE ON YOUR LEDGER.

**Comment by Duff-Paddy** [comment]
Tronfrance, thank you for the quick replay and clarification. It's probably best I don't do a full restore as it will be hassle with the other accounts on there.

Just for my sanity and peace of mind, essentially all I need is the Ledger to log into the account?
To recover my funds in case of loss of ledger I'd just restore to a new device using my seed words and could then easily log back into my tronscan wallet (no need to private key or keystore file)?

I just want to make sure before I start sending funds to this wallet, appreciate the advice.

**Comment by tronfrance** [comment]
Dear Duff-Daddy ,

Thank you for your interest about TRON-FRANCE.
Our technical expert will come back to you this afternoon.
Thank you for your patience.

regards

Christian

2018-07-13 10:19 GMT+02:00 Duff-Paddy <notifications@github.com>:

**Comment by tronfrance** [comment]
Duff-Daddy,

Just for my sanity and peace of mind, essentially all I need is the Ledger to log into the account?
To recover my funds in case of loss of ledger I'd just restore to a new device using my seed words and could then easily log back into my tronscan wallet (no need to private key or keystore file)?
**==> This is perfectly correct !**

By the way TRON-FRANCE takes this opportunity to congratulate Rovak and Fernando on the Ledger development.

**Comment by Duff-Paddy** [comment]
Thank you again
