### ISSUE TITLE
tronscan not accepting any withdrawal adresses

### ISSUE THREAD

**Issue by zahyar** [tronscan/tronscan-desktop#33]
i try to move my trx from tronscan wallet and its impossible to put a receiver adress cause it tells me : please put a valid adress... i don´t know how to fix it .can you help me??

**Comment by Rovak** [comment]
What address are you trying to input?

**Comment by Steelmark** [comment]
Use the copy function to get the address, then click the curser on the address box, now go to the drop down "EDIT" at the top left of the page, click on it, then paste and the address should show up in the address box.
