### ISSUE TITLE
trnscan error

### ISSUE THREAD

**Issue by rggrb** [tronscan/tronscan-desktop#36]
I have a problem with the tronscan when trying to enter with ledger nano says there is not an open portfolio to show

**Comment by rggrb** [comment]
who can be written to try to solve ?

**Comment by Makazar** [comment]
I too have the same problem. "No open wallet to view" appears every time I try to sign in.

**Comment by SoterDarkknight** [comment]
I have the same problem

**Comment by polaks** [comment]
network is down
the wallet has nothing to do with it

**Comment by rggrb** [comment]
Where can I place a claim?

**Comment by polaks** [comment]
There is a block causing a problem on the network after tvm activation.
The tron dev team is busy resolving and solution soon to follow.
