### ISSUE TITLE
Segfaults and coredumps on Ubuntu 18.10

### ISSUE THREAD

**Issue by travisbeale** [tronscan/tronscan-desktop#40]

**Comment by fouadr** [comment]
Same here:

Nov 13 22:58:15  kernel: [  567.650245] Tronscan[3572]: segfault at a4fa30 ip 0000000000a4fa30 sp 00007fff2ba4fd68 error 15 in Tronscan[200000+1602000]
Nov 13 22:58:15  kernel: [  567.650249] Code: da 9d ef 9d e6 9d f2 9d f8 9d 0c 9e fa 9d 1b 9e 64 76 58 76 67 76 02 76 46 76 47 76 49 76 1e 76 3b 76 6d 76 6e 76 69 76 72 76 <c7> 7a b6 7a 60 89 33 89 5d 89 47 89 38 89 64 89 b8 76 2e 80 2c 80

Ubuntu 18.10, 64bit.
