### ISSUE TITLE
Wallet address is hidden for receiving coins

### ISSUE THREAD

**Issue by raminious** [tronscan/tronscan-desktop#44]
I tried to open wallet with my Ledger Nano S. but the receiving address is empty!

![image](https://user-images.githubusercontent.com/334716/48922497-442f1a00-eebc-11e8-9b57-e776c7dad93d.png)

![image](https://user-images.githubusercontent.com/334716/48922501-51e49f80-eebc-11e8-996c-9d8e5c1793f4.png)

**Comment by raminious** [comment]
also, this issue isn't always reproducible. it works when I logout/login or restart the app for a couple of times

**Comment by douglasdeodato** [comment]
I have the same issue @raminious

**Comment by atmosblack** [comment]
Yes, I have the same problem with my new Nano S, but it doesn't matter how often I restart the app, I can't see my address. I just bought the Ledger for Tron, but this way it is useless for me.

**Comment by douglasdeodato** [comment]
yeah I tried use on my ledger nano, so I move on to use their website instead, wait a bit to this get better versions.

**Comment by skord0** [comment]
Same problem here.  Is anybody working on this?

**Comment by atmosblack** [comment]
@all I think no one is working on the tronscan desktop app, which makes it hard to trust in combination with the ledger in general.
I found a workaround though: Right above the login button you can see the Tron address. You have to send some TRX there to start.
Then you open the tronscan desktop app and only after that plugin your ledger and login. 
This worked for me, but again, I won't use it this way and trust my TronWatch wallet more to store my TRX.

**Comment by GarethTRelph** [comment]
Why are so many having this problem but still no one seems to fixing it

**Comment by Technard** [comment]
Everything is looking good now...I can vote ...Login.... all! Thanks everyone!
