### ISSUE TITLE
Abandoned Project ?

### ISSUE THREAD

**Issue by douglasdeodato** [tronscan/tronscan-desktop#45]
is this project abandoned ?

are tron developers responsible for that project?

**Comment by Stevemoody86** [comment]
I wondered the same thing as havent seen an update since July

**Comment by digimoneydgm** [comment]
looks like its a dead project, many issues with ledger and no answer

**Comment by Rovak** [comment]
please use https://tronscan.github.io/tronscan-frontend/#/ for the latest version which supports ledger
