### ISSUE TITLE
New Ledger Nano S opens a wallet without an address

### ISSUE THREAD

**Issue by atmosblack** [tronscan/tronscan-desktop#46]
Hi!

I just bought a new Ledger Nano S and everything seemed to work fine, but when I open the wallet in the Tronscan desktop app for MacOS, it opens a wallet without an address. 

<img width="499" alt="tronscan_1" src="https://user-images.githubusercontent.com/45369241/49035334-c2d5d100-f1b4-11e8-9f41-5be2bcfa81a7.png">
<img width="1135" alt="tronscan_2" src="https://user-images.githubusercontent.com/45369241/49035364-d123ed00-f1b4-11e8-9932-5a10f55d1d5b.png">

**Comment by Steelmark** [comment]
Hi, I had the same issue, send some TRX to the wallet address that shows up at "Load Ledger Wallet" and the next time you log in the address will show along with your balance.
