### ISSUE TITLE
Error: Freezing TRX with Ledger Nano S 

### ISSUE THREAD

**Issue by BillioniresMind** [tronscan/tronscan-desktop#47]
I get an error message when freezing TRX using Ledger Nano S "Error
Something went wrong while trying to freeze TRX".

This has been going on about 3 days.

Any advice?
![freeze trx](https://user-images.githubusercontent.com/39076539/49051498-0abe1d80-f1e0-11e8-86c9-fb7a69d1703b.png)

Regards.

**Comment by Steelmark** [comment]
Yes same error for the last several days, also get it on vote and send confirmation. have to login and out several time to get to take effect.

**Comment by BillioniresMind** [comment]
Thanks for the tip @Steelmark

**Comment by tlarock80** [comment]
same here ...Yes same error for the last several days, also get it on vote and send confirmation. have to login and out several time to get to take effect.

**Comment by BillioniresMind** [comment]
@tlarock80 I'm not sure if this project has been abandoned. It was the best TRX wallet until I started receiving the error message, couldn't freeze TRX and couldn't vote. Hope the developer is still around to sort it out.

**Comment by jakubsn** [comment]
same here

**Comment by BillioniresMind** [comment]
Hi all, I've been able to vote, freeze and check my account using the Ledger Nano S. Here's the link to use TronScan again... https://tronscan.github.io/tronscan-frontend/#/

**Comment by lekhanhtrinhbp** [comment]
I faced same error for freezing TRX with Ledger Nano S. Run on Windows 10 1903, Chrome 75.0.3770.142
