### ISSUE TITLE
Create token bug - one token per account warning false positive validation

### ISSUE THREAD

**Issue by corytam** [tronscan/tronscan-desktop#5]
**Issue** 

"You may only create one token per account" message shows when attempting to create token.
Tokens> Create > Shows me the create token form for a few seconds before message shows up.

![image](https://user-images.githubusercontent.com/3207685/42723126-b4bc39ea-878a-11e8-8fd0-d2d800d75424.png)

Bug can be replicated

**Settings**
Using ledger wallet on tron desktop app (Windows x64) 1.1.0 - ledger suppport
Had no tokens in wallet and bug occurred , tokens sent over and bug still occurred

Please donate to my tron address to support my bug exploration hunts :p 
TARUFU9gQGYmgTnZhEJutvx7pqFN9pwzvK

**Comment by bestboom** [comment]
I am also facing same

**Comment by Zenmann** [comment]
Facing same
