### ISSUE TITLE
using ledger nano S for basic opperation often ends with error

### ISSUE THREAD

**Issue by jakubsn** [tronscan/tronscan-desktop#51]
i have been using mac os version of tronscan with ledger stored private key for basic operations 👍 

send, vote, freeze

lately i need to repeat the operation many times before i get a success notification

sometimes the operation gets through even though the dialog message was error but most of the times it just fails to execute

i believe the problem can be somehow linked also to the status of login as it usually helps to quit tronscan and start it again without closing ledger 

if you are interested i can report on some of the problems in more detail ...

thank you

jakub

**Comment by Remaster007** [comment]
I had the same issue as you. Since 3 days it got worse. When I now open Tronscan Desktop it does not load any data. I do not see any information the app should grab out of the Tron Blockchain. Just the current TRX price is shown, nothing else, no possibility to send, receive or vote.

I use it on a Mac. Anybody help?

**Comment by fomman** [comment]
hey guys, its been fixed already....
Here is the link: https://tronscan.github.io/tronscan-frontend/#/
Plus, let you know that you can use TronWach app as well, it does support Ledger since yesterday.
P.s all apps available on Mac

**Comment by Discod73** [comment]
Tried that solution, chosing Ledger for wallet login, "Open the tron app on your ledger" just keeps loading or whatever, nothing happens. App problems remains the same as Remaster007´s problems.

**Comment by Remaster007** [comment]
I guess the desktop app is dead and gets no further development. However the web app is what will be used in the future and here I can login with my Ledger Nano S and see my funds. I'm also able to freeze TRX but still can not vote. When I define my votes and hit "Submit" it does not respond anymore. My existing votes can not be changed. Hopefully this gets resolved soon.
