### ISSUE TITLE
using tronscan with ledger nano and trading

### ISSUE THREAD

**Issue by finehobby** [tronscan/tronscan-desktop#56]
Hello I use https://tronscan.github.io/tronscan-frontend/# with ledger nano to handle my trx token
, just like you recommend, but i connot trade with this account at dex yet? When will it work?

**Comment by finehobby** [comment]
@ tron developer:
please see too to issue #34

**Comment by finehobby** [comment]
Dear TRON Team
still no solution in sight ??

**Comment by peteroosterbroek** [comment]
> Hello I use https://tronscan.github.io/tronscan-frontend/# with ledger nano to handle my trx token
> , just like you recommend, but i connot trade with this account at dex yet? When will it work?

I have the same problem and I cannot send TRX to another account!!
