### ISSUE TITLE
Windows Defender and Anti-Malwarebytes detects Tronscan.exe as trojan

### ISSUE THREAD

**Issue by plumelz** [tronscan/tronscan-desktop#60]
As the title says, both windows defender and AMB shows tronscan.exe including a trojan.

I've run tronscan.exe through virustotal, and has a detection ratio of 25/69. Link: https://www.virustotal.com/nl/file/4b8e22b0380ca703b26540bd43b44d3d4cfe086d63a7cf6a57b59aab40511e12/analysis/1545149779/
This seems super high?

Any ideas?

**Comment by Vokun21** [comment]
Version 1.1.1 is a Trojan. Version 1.1.0 is fine.

**Comment by Optimatum89** [comment]
Confirmed 1.1.0 is clean after scanning with Kaspersky Internet Security and Windows Defender.
