### ISSUE TITLE
Unable to Download/Install Tronscan

### ISSUE THREAD

**Issue by Vodafisher** [tronscan/tronscan-desktop#62]
I have been trying to download Tronscan for the past hour. 

**Let me explain:**

Every time I download the Tronscan zip file, I find only a read me file inside the zipped folder. This file cannot be opened by any known application on my laptop. If I try to open it with Notes, it shows me the links to the page where I have downloaded the file, but nothing else.

I have tried to watch a tutorial on youtube, but even there, when you download the zipped file you should have a lot of files inside, including a setup one which I can't find on my one.

Can anyone help please?

Thanks

**Comment by mac1gregor** [comment]
I also have this problem :(

**Comment by 11MAJ11** [comment]
Same issue here, all releases have same issue. This is odd !

**Comment by Rovak** [comment]
use https://tronscan.github.io/tronscan-frontend/#/, the tronscan desktop has been deprecated
