### ISSUE TITLE
reward tokens balance 0 even if transaction history log says otherwise

### ISSUE THREAD

**Issue by bogdan73** [tronscan/tronscan-desktop#63]
Up until yesterday my TERC reward tokens were coming in as usual. Since yesterday even if incoming transactions appear in transaction history logs the TERC balance of my wallet is 0.

**Comment by bogdan73** [comment]
If I check my wallet public address using https://tronscan.org/#/ all appears ok with TERC tokens in the wallet. If I use https://tronscan.github.io/tronscan-frontend/#/account or my Tronscan Desktop Wallet there are no tokens in my wallet. Hope this helps someone fix the problem as I cannot acces my wallet through https://tronscan.org/#/  having my TRX wallet on Ledger Nano S.

**Comment by morristico** [comment]
i posted the exact post on facebook to see if i got any respond and nothing i have the same problem since i don't have private key, only ledger i just stop voting for tron europe and voted for someone that gives me TRX, at least until the problem is fix, oh and i cant even move the old TREC to my other account where a used to sell them from.

**Comment by bogdan73** [comment]
So... Tronscan seems to behave like Bermuda Triangle lately. Starting from my previous concerns in this thread not only that nothing was fixed until now but things got even more peculiar. If I search my TRX address on https://tronscan.org/#/ today, ublike yesterday, I get results for a different address: TMuA6YqfCeX8EhbfYEg5y7S4DqzSJireY9 to be acurate. No matter the browser I use, Tronscan redirects my token balance query to this address. It is not April fool's day guys. Is someone able to explain me anything and restore things to normal?
