### ISSUE TITLE
Unable to Access Wallet on Tronscan

### ISSUE THREAD

**Issue by micjac14** [tronscan/tronscan-desktop#64]

**Comment by micjac14** [comment]
I desparately need help with a problem....I went to Tronscan page and requested to open a wallet.  After I connected my Nano s Ledger, it told me ledger was connected and gave me a wallet address.  I have since sent TRX to that address and can see it but don't know how to access it.  Please can someone assist me in what to do...

**Comment by BillioniresMind** [comment]
@micjac14 use this to access your TRX on tronscan... https://tronscan.github.io/tronscan-frontend/#/
