### ISSUE TITLE
Send TRC10 with ledger nano S

### ISSUE THREAD

**Issue by benjo1717** [tronscan/tronscan-desktop#65]
Hi, i m trying to send TRC10 from my tronscan account with my ledger nano S but i still get the following message: "Something went wrong while submitting the transaction".

Could you help me?
thank

**Comment by bogdan73** [comment]
Are you able to see your tokens in your wallet? What client do you use? Desktop? Browser? Which browser?

**Comment by benjo1717** [comment]
Yes i can see my token.
I tried with tronscan desktop , tronscan github frontend and tronwatch...

**Comment by yorkshirerippler** [comment]
I have exactly the same problem....loads of air drop coins which I can`t send anywhere to sell them.

Any help would be greatly appreciated :-)

**Comment by regnert** [comment]
same

**Comment by bogdan73** [comment]
any change?

**Comment by regnert** [comment]
Yes, busy worked. Thanks!

**Comment by regnert** [comment]
Well, maybe not. Can see transactions going through now, balance on
frontend doesn't reflect transfer though

**Comment by Seismicslob** [comment]
Im having the same issue with Tronscan and Ledger Nano S. Is there a fix yet?

**Comment by benjo1717** [comment]
Yes, u can send trc10 drop ledger with tronwatch desktop beta V1.0.13

**Comment by yorkshirerippler** [comment]
So it seems not only are my air dropped coins stuck but also I cannot unfreeze my TRX which means they are stuck too! It`s been more than three days since i froze any so that is not the reason.

Getting worried now

**Comment by yorkshirerippler** [comment]
After several attempts...logging out and back in again I have managed to unfreeze and send my TRX to the web version of Tronscan.

It`s now just the freebies which are stuck which is annoying but not as bad as not being able to move the TRX

**Comment by bogdan73** [comment]
> After several attempts...logging out and back in again I have managed to unfreeze and send my TRX to the web version of Tronscan.
> 
> It`s now just the freebies which are stuck which is annoying but not as bad as not being able to move the TRX

What do you mean by "send my TRX to the web version of Tronscan"? You have one address for the TRX wallet no matter the wallet you are using, desktop or web.

I am still stuck. Desktop not working on Mac OS, web version no working, TronWatch not working.

**Comment by yorkshirerippler** [comment]
Hi,

Some how I have got two different addresses so i guess I have two different accounts, I don`t seem to have the private key for the desktop version. I log in with my ledger.

With the web version you can`t log in with ledger so I can`t access that account on the web version

**Comment by yorkshirerippler** [comment]
So I can now log in to the browser version with my ledger....problem solved...excellent...thanks for your help!
