### ISSUE TITLE
Can't withdraw from Tron Scan or Tron Link!

### ISSUE THREAD

**Issue by so-sweet** [tronscan/tronscan-desktop#72]
I installed the new Tron Link but it is still not letting me withdraw my Tron.  Can the developers help me with this?  I tried Tronscan too, but no luck

**Comment by mathinath** [comment]
Use the link https://tronscan.org/#/

**Comment by Alotofwhoknowswhat** [comment]
Thank you!  I was finally able to withdraw them. I think Tron Link was not working so I did withdraw them from Tronscan. Thanks for your help
