### ISSUE TITLE
Cannot access Tronscan since BTT Airdrop

### ISSUE THREAD

**Issue by GarethTRelph** [tronscan/tronscan-desktop#73]
Since the BTT airdrop I am unable to access my TRX on Tronscan.org or through github. I can enter my Nano Ledger on github/tronsc but I just get a message saying No Wallet
With Tronscan.org the screen just remains white.
The last time I was able to log in the blockheight was 6591982 A few hours later I was unable to log in anymore.

**Comment by mathinath** [comment]
Use the link below,

https://tronscan.org/#/

**Comment by GarethTRelph** [comment]
Hi, Thanks for this. It was this link that wasnt working but it was because
Java had somehow become corrupted. I installed the latest Java and now it
all works again.
I am now deleting all my saved passwords and changing them all on the
respective websites. Also switching away from Google and using DuckDuckGo.
I can see new websites and saved passwords appearing on my Google saved
passwords list that are not mine. I believe they are linked to a PC at the
office of a company I sold 2 years ago. I deleted all my history before I
left it but somehow they are still syncing to my Google account.
Worrying me a bit.
Thankyou very much for your response.

**Comment by 240516** [comment]
Hi Gareth TRelph
Mate can you please guide me how to check that java is corrupted and how to install new one and how i can claim Btt tokens from tronscan. 
Your reply would be much appreciated.

**Comment by GarethTRelph** [comment]
Hi, I am not an expert in this field. I just re-downloaded Java and
everything started working again. If you had TRX in a Tron related wallet
when the Blockheight reached 6.6 million and are in a country which is not
restricted, you would have got the equivalent quantity in BTT.
