### ISSUE TITLE
no open wallet to view

### ISSUE THREAD

**Issue by ashwaninagrani** [tronscan/tronscan-desktop#75]
hello guys , can anyone help me out,i am getting same message no open wallet or i saved my trx there.
suggestion appreciated.
thanks

**Comment by Rovak** [comment]
please use https://tronscan.org. the desktop client has been deprecated

**Comment by ashwaninagrani** [comment]
thanks rovak i will check and let you know if it works.

**Comment by monatwin2ron** [comment]
My tron disappeared on tronscan.Additionally I was not able to execute to
freeze my tron.6981.04 tron I cannot locate....Please advise.

**Comment by monatwin2ron** [comment]
Not transfer my tron
