### ISSUE TITLE
unable to unfreeze or freeze token with Ledger

### ISSUE THREAD

**Issue by mac1gregor** [tronscan/tronscan-desktop#76]
Has anybody had issues with freezing or unfreezing trx with ledger on the tron blockchain explorer????

**Comment by mac1gregor** [comment]
I hate Tron desktop it is terrible.
I think if Tron cannot get this right I will cash out and jump over to ada!!!

**Comment by Rovak** [comment]
do you use https://tronscan.org? the desktop client has been deprecated

**Comment by wongzhunhou** [comment]
Yes, it is taking forever to freeze and vote. Please solve it ASAP

**Comment by douglasdeodato** [comment]
try use: https://tronscan.org
