### ISSUE TITLE
Symantec Antivirus Issues

### ISSUE THREAD

**Issue by ykaravas** [tronscan/tronscan-desktop#9]
Symantec Antivirus identifies some aspects of tronscan desktop app, namely those in C:/Users/<user>/AppData/local/Temp as viruses and quarantines them. Exceptions can be made for C:/Users/<user>/AppData/Roaming/tr, C:/Users/<user>/AppData/Roaming/Tronscan and C:/Users/<user>/AppData/Roaming/trons-explorer-desktop. C:/Users/<user>/AppData/local/Temp issues persist with Antivirus conflicts, however.

**Comment by Rovak** [comment]
This is a known issue https://github.com/electron/electron/issues/4485
